# Generated by Django 5.0 on 2023-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_date_end_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('option1', 'In progress'), ('option2', 'Done')], max_length=100, null=True),
        ),
    ]
